spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notification_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notification_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

notification.nats.enabled=true
notification.nats.server-url=${NATS_SERVER_URL:nats://nats:4222}
